import { Button } from "@/components/ui/button";
import { Download } from "lucide-react";
import { toast } from "sonner";
import { type AnalysisData, type AIAnalysisResult } from "@/lib/analysisStore";

interface PDFExportProps {
  data: AnalysisData;
  aiResult: AIAnalysisResult | null;
}

const PDFExport = ({ data, aiResult }: PDFExportProps) => {
  const handleExport = () => {
    const { role, state, lang, modules } = data;

    let content = `AI PARLIAMENT - LAW IMPACT ANALYSIS REPORT\n`;
    content += `${"=".repeat(50)}\n\n`;
    content += `Generated: ${new Date().toLocaleString("en-IN")}\n`;
    content += `Role: ${role === "central" ? "Central Government" : `State Government (${state})`}\n`;
    content += `Language: ${lang === "en" ? "English" : "Hindi"}\n\n`;

    if (modules.modLegal && aiResult?.modLegal) {
      content += `LEGAL OVERVIEW\n${"-".repeat(30)}\n`;
      content += `${aiResult.modLegal.summary_en}\n`;
      content += `Status: ${aiResult.modLegal.status} | Confidence: ${aiResult.modLegal.confidence}%\n\n`;
    }

    if (modules.modEconomic && aiResult?.modEconomic) {
      content += `ECONOMIC IMPACT\n${"-".repeat(30)}\n`;
      content += `Revenue Impact: ${aiResult.modEconomic.revenueImpact}\n`;
      content += `Compliance Savings: ${aiResult.modEconomic.complianceSavings}\n`;
      content += `Job Creation: ${aiResult.modEconomic.jobCreation}\n`;
      content += `${aiResult.modEconomic.details}\n\n`;
    }

    if (modules.modGeo && aiResult?.modGeo) {
      content += `GEOGRAPHIC ANALYSIS\n${"-".repeat(30)}\n`;
      content += `High Readiness: ${aiResult.modGeo.highReadiness?.join(", ")}\n`;
      content += `Medium Readiness: ${aiResult.modGeo.mediumReadiness?.join(", ")}\n`;
      content += `Need Support: ${aiResult.modGeo.needSupport?.join(", ")}\n\n`;
    }

    if (modules.modCommunity && aiResult?.modCommunity) {
      content += `COMMUNITY IMPACT\n${"-".repeat(30)}\n`;
      content += `${aiResult.modCommunity.summary}\n`;
      content += `Recommendations:\n`;
      aiResult.modCommunity.recommendations?.forEach((r, i) => {
        content += `  ${i + 1}. ${r}\n`;
      });
      content += "\n";
    }

    if (modules.modGender && aiResult?.modGender) {
      content += `GENDER IMPACT\n${"-".repeat(30)}\n`;
      content += `${aiResult.modGender.summary}\n`;
      content += `Women Benefit: ${aiResult.modGender.womenBenefit}\n\n`;
    }

    if (modules.modGlobal && aiResult?.modGlobal) {
      content += `GLOBAL COMPARISON\n${"-".repeat(30)}\n`;
      aiResult.modGlobal.comparisons?.forEach((c) => {
        content += `  ${c.country} (${c.policy}): ${c.outcome}\n`;
      });
      content += "\n";
    }

    if (modules.modPrevious && aiResult?.modPrevious) {
      content += `LESSONS FROM PAST REFORMS\n${"-".repeat(30)}\n`;
      aiResult.modPrevious.lessons?.forEach((l, i) => {
        content += `  ${i + 1}. ${l}\n`;
      });
      content += "\n";
    }

    if (modules.modFuture && aiResult?.modFuture) {
      content += `3-YEAR PROJECTIONS\n${"-".repeat(30)}\n`;
      content += `Optimistic: ${aiResult.modFuture.optimistic?.formalization} formalization, ${aiResult.modFuture.optimistic?.revenue} revenue\n`;
      content += `Neutral: ${aiResult.modFuture.neutral?.formalization} formalization, ${aiResult.modFuture.neutral?.revenue} revenue\n`;
      content += `Cautious: ${aiResult.modFuture.cautious?.formalization} formalization, ${aiResult.modFuture.cautious?.revenue} revenue\n\n`;
    }

    content += `${"=".repeat(50)}\n`;
    content += `AI Parliament - Academic Prototype\n`;
    content += `This report was generated by AI and is for informational purposes only.\n`;

    const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `AI-Parliament-Report-${new Date().toISOString().split("T")[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Report downloaded!");
  };

  return (
    <Button variant="outline" onClick={handleExport} className="gap-2">
      <Download className="w-4 h-4" />
      Export Report
    </Button>
  );
};

export default PDFExport;
